using Game_Elements.Enums;
using Game_Elements.Models;

namespace Game_Elements.Factories
{
    public static class ResearchTreeFactory
    {
        public static List<ResearchNode> GetResearchTree()
        {
            return
                [
                new ResearchNode { Name = "Mission Experience Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience amount by 5%" },
                new ResearchNode { Name = "Mission Experience Amount 2", Prerequisites = ["Mission Experience Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience amount by 5%" },
                new ResearchNode { Name = "Mission Experience Amount 3", Prerequisites = ["Mission Experience Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience amount by 5%" },
                new ResearchNode { Name = "Mission Experience Amount 4", Prerequisites = ["Mission Experience Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience amount by 5%" },
                new ResearchNode { Name = "Mission Experience Amount 5", Prerequisites = ["Mission Experience Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience amount by 5%" },

                new ResearchNode { Name = "Mission Gold Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission gold amount by 5%" },
                new ResearchNode { Name = "Mission Gold Amount 2", Prerequisites = ["Mission Gold Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission gold amount by 5%" },
                new ResearchNode { Name = "Mission Gold Amount 3", Prerequisites = ["Mission Gold Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission gold amount by 5%" },
                new ResearchNode { Name = "Mission Gold Amount 4", Prerequisites = ["Mission Gold Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission gold amount by 5%" },
                new ResearchNode { Name = "Mission Gold Amount 5", Prerequisites = ["Mission Gold Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission gold amount by 5%" },

                new ResearchNode { Name = "Mission Power Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionPowerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission power odds by 1%" },
                new ResearchNode { Name = "Mission Power Odds 2", Prerequisites = ["Mission Power Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionPowerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission power odds by 1%" },
                new ResearchNode { Name = "Mission Power Odds 3", Prerequisites = ["Mission Power Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionPowerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission power odds by 1%" },
                new ResearchNode { Name = "Mission Power Odds 4", Prerequisites = ["Mission Power Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionPowerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission power odds by 1%" },
                new ResearchNode { Name = "Mission Power Odds 5", Prerequisites = ["Mission Power Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionPowerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission power odds by 1%" },

                new ResearchNode { Name = "Mission Water Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionWaterOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission water odds by 1%" },
                new ResearchNode { Name = "Mission Water Odds 2", Prerequisites = ["Mission Water Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionWaterOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission water odds by 1%" },
                new ResearchNode { Name = "Mission Water Odds 3", Prerequisites = ["Mission Water Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionWaterOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission water odds by 1%" },
                new ResearchNode { Name = "Mission Water Odds 4", Prerequisites = ["Mission Water Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionWaterOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission water odds by 1%" },
                new ResearchNode { Name = "Mission Water Odds 5", Prerequisites = ["Mission Water Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionWaterOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission water odds by 1%" },

                new ResearchNode { Name = "Mission Food Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFoodOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission food odds by 1%" },
                new ResearchNode { Name = "Mission Food Odds 2", Prerequisites = ["Mission Food Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFoodOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission food odds by 1%" },
                new ResearchNode { Name = "Mission Food Odds 3", Prerequisites = ["Mission Food Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFoodOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission food odds by 1%" },
                new ResearchNode { Name = "Mission Food Odds 4", Prerequisites = ["Mission Food Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFoodOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission food odds by 1%" },
                new ResearchNode { Name = "Mission Food Odds 5", Prerequisites = ["Mission Food Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFoodOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission food odds by 1%" },

                new ResearchNode { Name = "Mission Concrete Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionConcreteOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission concrete odds by 1%" },
                new ResearchNode { Name = "Mission Concrete Odds 2", Prerequisites = ["Mission Concrete Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionConcreteOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission concrete odds by 1%" },
                new ResearchNode { Name = "Mission Concrete Odds 3", Prerequisites = ["Mission Concrete Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionConcreteOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission concrete odds by 1%" },
                new ResearchNode { Name = "Mission Concrete Odds 4", Prerequisites = ["Mission Concrete Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionConcreteOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission concrete odds by 1%" },
                new ResearchNode { Name = "Mission Concrete Odds 5", Prerequisites = ["Mission Concrete Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionConcreteOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission concrete odds by 1%" },

                new ResearchNode { Name = "Mission Metal Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMetalOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission metal odds by 1%" },
                new ResearchNode { Name = "Mission Metal Odds 2", Prerequisites = ["Mission Metal Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMetalOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission metal odds by 1%" },
                new ResearchNode { Name = "Mission Metal Odds 3", Prerequisites = ["Mission Metal Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMetalOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission metal odds by 1%" },
                new ResearchNode { Name = "Mission Metal Odds 4", Prerequisites = ["Mission Metal Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMetalOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission metal odds by 1%" },
                new ResearchNode { Name = "Mission Metal Odds 5", Prerequisites = ["Mission Metal Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMetalOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission metal odds by 1%" },

                new ResearchNode { Name = "Mission Item Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionItemOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission item odds by 1%" },
                new ResearchNode { Name = "Mission Item Odds 2", Prerequisites = ["Mission Item Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionItemOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission item odds by 1%" },
                new ResearchNode { Name = "Mission Item Odds 3", Prerequisites = ["Mission Item Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionItemOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission item odds by 1%" },
                new ResearchNode { Name = "Mission Item Odds 4", Prerequisites = ["Mission Item Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionItemOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission item odds by 1%" },
                new ResearchNode { Name = "Mission Item Odds 5", Prerequisites = ["Mission Item Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionItemOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission item odds by 1%" },

                new ResearchNode { Name = "Mission Unit Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionUnitOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission unit odds by 1%" },
                new ResearchNode { Name = "Mission Unit Odds 2", Prerequisites = ["Mission Unit Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionUnitOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission unit odds by 1%" },
                new ResearchNode { Name = "Mission Unit Odds 3", Prerequisites = ["Mission Unit Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionUnitOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission unit odds by 1%" },
                new ResearchNode { Name = "Mission Unit Odds 4", Prerequisites = ["Mission Unit Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionUnitOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission unit odds by 1%" },
                new ResearchNode { Name = "Mission Unit Odds 5", Prerequisites = ["Mission Unit Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionUnitOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission unit odds by 1%" },

                new ResearchNode { Name = "Mission Lootbox Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionLootboxOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission lootbox odds by 1%" },
                new ResearchNode { Name = "Mission Lootbox Odds 2", Prerequisites = ["Mission Lootbox Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionLootboxOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission lootbox odds by 1%" },
                new ResearchNode { Name = "Mission Lootbox Odds 3", Prerequisites = ["Mission Lootbox Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionLootboxOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission lootbox odds by 1%" },
                new ResearchNode { Name = "Mission Lootbox Odds 4", Prerequisites = ["Mission Lootbox Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionLootboxOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission lootbox odds by 1%" },
                new ResearchNode { Name = "Mission Lootbox Odds 5", Prerequisites = ["Mission Lootbox Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionLootboxOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission lootbox odds by 1%" },

                new ResearchNode { Name = "Mission Rush Boost Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRushBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rush boost odds by 1%" },
                new ResearchNode { Name = "Mission Rush Boost Odds 2", Prerequisites = ["Mission Rush Boost Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRushBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rush boost odds by 1%" },
                new ResearchNode { Name = "Mission Rush Boost Odds 3", Prerequisites = ["Mission Rush Boost Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRushBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rush boost odds by 1%" },
                new ResearchNode { Name = "Mission Rush Boost Odds 4", Prerequisites = ["Mission Rush Boost Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRushBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rush boost odds by 1%" },
                new ResearchNode { Name = "Mission Rush Boost Odds 5", Prerequisites = ["Mission Rush Boost Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRushBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rush boost odds by 1%" },

                new ResearchNode { Name = "Mission Experience Boost Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience boost odds by 1%" },
                new ResearchNode { Name = "Mission Experience Boost Odds 2", Prerequisites = ["Mission Experience Boost Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience boost odds by 1%" },
                new ResearchNode { Name = "Mission Experience Boost Odds 3", Prerequisites = ["Mission Experience Boost Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience boost odds by 1%" },
                new ResearchNode { Name = "Mission Experience Boost Odds 4", Prerequisites = ["Mission Experience Boost Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience boost odds by 1%" },
                new ResearchNode { Name = "Mission Experience Boost Odds 5", Prerequisites = ["Mission Experience Boost Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionExperienceBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission experience boost odds by 1%" },

                new ResearchNode { Name = "Mission Rarity Boost Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRarityBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rarity boost odds by 1%" },
                new ResearchNode { Name = "Mission Rarity Boost Odds 2", Prerequisites = ["Mission Rarity Boost Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRarityBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rarity boost odds by 1%" },
                new ResearchNode { Name = "Mission Rarity Boost Odds 3", Prerequisites = ["Mission Rarity Boost Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRarityBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rarity boost odds by 1%" },
                new ResearchNode { Name = "Mission Rarity Boost Odds 4", Prerequisites = ["Mission Rarity Boost Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRarityBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rarity boost odds by 1%" },
                new ResearchNode { Name = "Mission Rarity Boost Odds 5", Prerequisites = ["Mission Rarity Boost Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionRarityBoostOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission rarity boost odds by 1%" },

                new ResearchNode { Name = "Mission Monster Egg Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMonsterEggOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission monster egg odds by 1%" },
                new ResearchNode { Name = "Mission Monster Egg Odds 2", Prerequisites = ["Mission Monster Egg Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMonsterEggOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission monster egg odds by 1%" },
                new ResearchNode { Name = "Mission Monster Egg Odds 3", Prerequisites = ["Mission Monster Egg Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMonsterEggOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission monster egg odds by 1%" },
                new ResearchNode { Name = "Mission Monster Egg Odds 4", Prerequisites = ["Mission Monster Egg Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMonsterEggOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission monster egg odds by 1%" },
                new ResearchNode { Name = "Mission Monster Egg Odds 5", Prerequisites = ["Mission Monster Egg Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMonsterEggOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission monster egg odds by 1%" },

                new ResearchNode { Name = "Mission Fertilizer Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFertilizerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission fertilizer odds by 1%" },
                new ResearchNode { Name = "Mission Fertilizer Odds 2", Prerequisites = ["Mission Fertilizer Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFertilizerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission fertilizer odds by 1%" },
                new ResearchNode { Name = "Mission Fertilizer Odds 3", Prerequisites = ["Mission Fertilizer Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFertilizerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission fertilizer odds by 1%" },
                new ResearchNode { Name = "Mission Fertilizer Odds 4", Prerequisites = ["Mission Fertilizer Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFertilizerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission fertilizer odds by 1%" },
                new ResearchNode { Name = "Mission Fertilizer Odds 5", Prerequisites = ["Mission Fertilizer Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionFertilizerOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission fertilizer odds by 1%" },

                new ResearchNode { Name = "Mission Mystery Seed Odds 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMysterySeedOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission mystery seed odds by 1%" },
                new ResearchNode { Name = "Mission Mystery Seed Odds 2", Prerequisites = ["Mission Mystery Seed Odds 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMysterySeedOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission mystery seed odds by 1%" },
                new ResearchNode { Name = "Mission Mystery Seed Odds 3", Prerequisites = ["Mission Mystery Seed Odds 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMysterySeedOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission mystery seed odds by 1%" },
                new ResearchNode { Name = "Mission Mystery Seed Odds 4", Prerequisites = ["Mission Mystery Seed Odds 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMysterySeedOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission mystery seed odds by 1%" },
                new ResearchNode { Name = "Mission Mystery Seed Odds 5", Prerequisites = ["Mission Mystery Seed Odds 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionMysterySeedOdds, ModifierType = ModifierType.Percent, ModifierAmount = 0.01, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mission mystery seed odds by 1%" },

                new ResearchNode { Name = "Research Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ResearchProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases research production amount by 1" },
                new ResearchNode { Name = "Research Production Amount 2", Prerequisites = ["Research Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ResearchProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases research production amount by 1" },
                new ResearchNode { Name = "Research Production Amount 3", Prerequisites = ["Research Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ResearchProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases research production amount by 1" },
                new ResearchNode { Name = "Research Production Amount 4", Prerequisites = ["Research Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ResearchProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases research production amount by 1" },
                new ResearchNode { Name = "Research Production Amount 5", Prerequisites = ["Research Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ResearchProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases research production amount by 1" },

                new ResearchNode { Name = "Power Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.PowerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases power production amount by 5" },
                new ResearchNode { Name = "Power Production Amount 2", Prerequisites = ["Power Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.PowerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases power production amount by 5" },
                new ResearchNode { Name = "Power Production Amount 3", Prerequisites = ["Power Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.PowerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases power production amount by 5" },
                new ResearchNode { Name = "Power Production Amount 4", Prerequisites = ["Power Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.PowerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases power production amount by 5" },
                new ResearchNode { Name = "Power Production Amount 5", Prerequisites = ["Power Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.PowerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases power production amount by 5" },

                new ResearchNode { Name = "Water Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.WaterProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases water production amount by 1" },
                new ResearchNode { Name = "Water Production Amount 2", Prerequisites = ["Water Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.WaterProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases water production amount by 1" },
                new ResearchNode { Name = "Water Production Amount 3", Prerequisites = ["Water Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.WaterProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases water production amount by 1" },
                new ResearchNode { Name = "Water Production Amount 4", Prerequisites = ["Water Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.WaterProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases water production amount by 1" },
                new ResearchNode { Name = "Water Production Amount 5", Prerequisites = ["Water Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.WaterProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases water production amount by 1" },

                new ResearchNode { Name = "Food Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FoodProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases food production amount by 1" },
                new ResearchNode { Name = "Food Production Amount 2", Prerequisites = ["Food Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FoodProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases food production amount by 1" },
                new ResearchNode { Name = "Food Production Amount 3", Prerequisites = ["Food Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FoodProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases food production amount by 1" },
                new ResearchNode { Name = "Food Production Amount 4", Prerequisites = ["Food Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FoodProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases food production amount by 1" },
                new ResearchNode { Name = "Food Production Amount 5", Prerequisites = ["Food Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FoodProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases food production amount by 1" },

                new ResearchNode { Name = "Concrete Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ConcreteProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases concrete production amount by 1" },
                new ResearchNode { Name = "Concrete Production Amount 2", Prerequisites = ["Concrete Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ConcreteProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases concrete production amount by 1" },
                new ResearchNode { Name = "Concrete Production Amount 3", Prerequisites = ["Concrete Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ConcreteProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases concrete production amount by 1" },
                new ResearchNode { Name = "Concrete Production Amount 4", Prerequisites = ["Concrete Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ConcreteProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases concrete production amount by 1" },
                new ResearchNode { Name = "Concrete Production Amount 5", Prerequisites = ["Concrete Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ConcreteProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases concrete production amount by 1" },

                new ResearchNode { Name = "Metal Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MetalProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases metal production amount by 1" },
                new ResearchNode { Name = "Metal Production Amount 2", Prerequisites = ["Metal Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MetalProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases metal production amount by 1" },
                new ResearchNode { Name = "Metal Production Amount 3", Prerequisites = ["Metal Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MetalProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases metal production amount by 1" },
                new ResearchNode { Name = "Metal Production Amount 4", Prerequisites = ["Metal Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MetalProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases metal production amount by 1" },
                new ResearchNode { Name = "Metal Production Amount 5", Prerequisites = ["Metal Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MetalProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases metal production amount by 1" },

                new ResearchNode { Name = "Gold Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GoldProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 25, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases gold production amount by 25" },
                new ResearchNode { Name = "Gold Production Amount 2", Prerequisites = ["Gold Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GoldProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 50, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases gold production amount by 50" },
                new ResearchNode { Name = "Gold Production Amount 3", Prerequisites = ["Gold Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GoldProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 75, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases gold production amount by 75" },
                new ResearchNode { Name = "Gold Production Amount 4", Prerequisites = ["Gold Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GoldProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 100, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases gold production amount by 100" },
                new ResearchNode { Name = "Gold Production Amount 5", Prerequisites = ["Gold Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GoldProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 125, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases gold production amount by 125" },

                new ResearchNode { Name = "Lootbox Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox production amount by 1" },
                new ResearchNode { Name = "Lootbox Production Amount 2", Prerequisites = ["Lootbox Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox production amount by 1" },
                new ResearchNode { Name = "Lootbox Production Amount 3", Prerequisites = ["Lootbox Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox production amount by 1" },
                new ResearchNode { Name = "Lootbox Production Amount 4", Prerequisites = ["Lootbox Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox production amount by 1" },
                new ResearchNode { Name = "Lootbox Production Amount 5", Prerequisites = ["Lootbox Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox production amount by 1" },

                new ResearchNode { Name = "Rush Boost Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RushBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rush boost production amount by 1" },
                new ResearchNode { Name = "Rush Boost Production Amount 2", Prerequisites = ["Rush Boost Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RushBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rush boost production amount by 1" },
                new ResearchNode { Name = "Rush Boost Production Amount 3", Prerequisites = ["Rush Boost Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RushBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rush boost production amount by 1" },
                new ResearchNode { Name = "Rush Boost Production Amount 4", Prerequisites = ["Rush Boost Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RushBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rush boost production amount by 1" },
                new ResearchNode { Name = "Rush Boost Production Amount 5", Prerequisites = ["Rush Boost Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RushBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rush boost production amount by 1" },

                new ResearchNode { Name = "Experience Boost Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost production amount by 1" },
                new ResearchNode { Name = "Experience Boost Production Amount 2", Prerequisites = ["Experience Boost Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost production amount by 1" },
                new ResearchNode { Name = "Experience Boost Production Amount 3", Prerequisites = ["Experience Boost Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost production amount by 1" },
                new ResearchNode { Name = "Experience Boost Production Amount 4", Prerequisites = ["Experience Boost Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost production amount by 1" },
                new ResearchNode { Name = "Experience Boost Production Amount 5", Prerequisites = ["Experience Boost Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost production amount by 1" },

                new ResearchNode { Name = "Rarity Boost Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RarityBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rarity boost production amount by 1" },
                new ResearchNode { Name = "Rarity Boost Production Amount 2", Prerequisites = ["Rarity Boost Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RarityBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rarity boost production amount by 1" },
                new ResearchNode { Name = "Rarity Boost Production Amount 3", Prerequisites = ["Rarity Boost Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RarityBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rarity boost production amount by 1" },
                new ResearchNode { Name = "Rarity Boost Production Amount 4", Prerequisites = ["Rarity Boost Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RarityBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rarity boost production amount by 1" },
                new ResearchNode { Name = "Rarity Boost Production Amount 5", Prerequisites = ["Rarity Boost Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.RarityBoostProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases rarity boost production amount by 1" },

                new ResearchNode { Name = "Monster Egg Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MonsterEggProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases monster egg production amount by 1" },
                new ResearchNode { Name = "Monster Egg Production Amount 2", Prerequisites = ["Monster Egg Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MonsterEggProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases monster egg production amount by 1" },
                new ResearchNode { Name = "Monster Egg Production Amount 3", Prerequisites = ["Monster Egg Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MonsterEggProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases monster egg production amount by 1" },
                new ResearchNode { Name = "Monster Egg Production Amount 4", Prerequisites = ["Monster Egg Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MonsterEggProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases monster egg production amount by 1" },
                new ResearchNode { Name = "Monster Egg Production Amount 5", Prerequisites = ["Monster Egg Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MonsterEggProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases monster egg production amount by 1" },

                new ResearchNode { Name = "Fertilizer Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FertilizerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases fertilizer production amount by 1" },
                new ResearchNode { Name = "Fertilizer Production Amount 2", Prerequisites = ["Fertilizer Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FertilizerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases fertilizer production amount by 1" },
                new ResearchNode { Name = "Fertilizer Production Amount 3", Prerequisites = ["Fertilizer Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FertilizerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases fertilizer production amount by 1" },
                new ResearchNode { Name = "Fertilizer Production Amount 4", Prerequisites = ["Fertilizer Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FertilizerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases fertilizer production amount by 1" },
                new ResearchNode { Name = "Fertilizer Production Amount 5", Prerequisites = ["Fertilizer Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.FertilizerProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases fertilizer production amount by 1" },

                new ResearchNode { Name = "Mystery Seed Production Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MysterySeedProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mystery seed production amount by 1" },
                new ResearchNode { Name = "Mystery Seed Production Amount 2", Prerequisites = ["Mystery Seed Production Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MysterySeedProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mystery seed production amount by 1" },
                new ResearchNode { Name = "Mystery Seed Production Amount 3", Prerequisites = ["Mystery Seed Production Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MysterySeedProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mystery seed production amount by 1" },
                new ResearchNode { Name = "Mystery Seed Production Amount 4", Prerequisites = ["Mystery Seed Production Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MysterySeedProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mystery seed production amount by 1" },
                new ResearchNode { Name = "Mystery Seed Production Amount 5", Prerequisites = ["Mystery Seed Production Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MysterySeedProductionAmount, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases mystery seed production amount by 1" },

                new ResearchNode { Name = "Max Quests 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxQuests, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum quests by 1" },
                new ResearchNode { Name = "Max Quests 2", Prerequisites = ["Max Quests 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxQuests, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum quests by 1" },
                new ResearchNode { Name = "Max Quests 3", Prerequisites = ["Max Quests 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxQuests, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum quests by 1" },

                new ResearchNode { Name = "Mission Duration 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases mission duration by 5%" },
                new ResearchNode { Name = "Mission Duration 2", Prerequisites = ["Mission Duration 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases mission duration by 5%" },
                new ResearchNode { Name = "Mission Duration 3", Prerequisites = ["Mission Duration 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases mission duration by 5%" },
                new ResearchNode { Name = "Mission Duration 4", Prerequisites = ["Mission Duration 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases mission duration by 5%" },
                new ResearchNode { Name = "Mission Duration 5", Prerequisites = ["Mission Duration 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MissionDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases mission duration by 5%" },

                new ResearchNode { Name = "Unit Success Chance 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitSuccessChance, ModifierType = ModifierType.Flat, ModifierAmount = 1, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases unit success chance by 1" },
                new ResearchNode { Name = "Unit Success Chance 2", Prerequisites = ["Unit Success Chance 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitSuccessChance, ModifierType = ModifierType.Flat, ModifierAmount = 2, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases unit success chance by 2" },
                new ResearchNode { Name = "Unit Success Chance 3", Prerequisites = ["Unit Success Chance 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitSuccessChance, ModifierType = ModifierType.Flat, ModifierAmount = 3, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases unit success chance by 3" },
                new ResearchNode { Name = "Unit Success Chance 4", Prerequisites = ["Unit Success Chance 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitSuccessChance, ModifierType = ModifierType.Flat, ModifierAmount = 4, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases unit success chance by 4" },
                new ResearchNode { Name = "Unit Success Chance 5", Prerequisites = ["Unit Success Chance 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitSuccessChance, ModifierType = ModifierType.Flat, ModifierAmount = 5, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases unit success chance by 5" },

                new ResearchNode { Name = "Lootbox Gold Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox gold amount by 5%" },
                new ResearchNode { Name = "Lootbox Gold Amount 2", Prerequisites = ["Lootbox Gold Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox gold amount by 5%" },
                new ResearchNode { Name = "Lootbox Gold Amount 3", Prerequisites = ["Lootbox Gold Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox gold amount by 5%" },
                new ResearchNode { Name = "Lootbox Gold Amount 4", Prerequisites = ["Lootbox Gold Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox gold amount by 5%" },
                new ResearchNode { Name = "Lootbox Gold Amount 5", Prerequisites = ["Lootbox Gold Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.LootboxGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases lootbox gold amount by 5%" },

                new ResearchNode { Name = "Quest Gold Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.QuestGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases quest gold amount by 5%" },
                new ResearchNode { Name = "Quest Gold Amount 2", Prerequisites = ["Quest Gold Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.QuestGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases quest gold amount by 5%" },
                new ResearchNode { Name = "Quest Gold Amount 3", Prerequisites = ["Quest Gold Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.QuestGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases quest gold amount by 5%" },
                new ResearchNode { Name = "Quest Gold Amount 4", Prerequisites = ["Quest Gold Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.QuestGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases quest gold amount by 5%" },
                new ResearchNode { Name = "Quest Gold Amount 5", Prerequisites = ["Quest Gold Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.QuestGoldAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases quest gold amount by 5%" },

                new ResearchNode { Name = "Unit Renaming Cost 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitRenamingCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit renaming cost by 5%" },
                new ResearchNode { Name = "Unit Renaming Cost 2", Prerequisites = ["Unit Renaming Cost 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitRenamingCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit renaming cost by 5%" },
                new ResearchNode { Name = "Unit Renaming Cost 3", Prerequisites = ["Unit Renaming Cost 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitRenamingCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit renaming cost by 5%" },
                new ResearchNode { Name = "Unit Renaming Cost 4", Prerequisites = ["Unit Renaming Cost 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitRenamingCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit renaming cost by 5%" },
                new ResearchNode { Name = "Unit Renaming Cost 5", Prerequisites = ["Unit Renaming Cost 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitRenamingCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit renaming cost by 5%" },

                new ResearchNode { Name = "Item Shop Cost 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemShopCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases item shop cost by 5%" },
                new ResearchNode { Name = "Item Shop Cost 2", Prerequisites = ["Item Shop Cost 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemShopCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases item shop cost by 5%" },
                new ResearchNode { Name = "Item Shop Cost 3", Prerequisites = ["Item Shop Cost 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemShopCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases item shop cost by 5%" },
                new ResearchNode { Name = "Item Shop Cost 4", Prerequisites = ["Item Shop Cost 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemShopCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases item shop cost by 5%" },
                new ResearchNode { Name = "Item Shop Cost 5", Prerequisites = ["Item Shop Cost 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemShopCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases item shop cost by 5%" },

                new ResearchNode { Name = "Egg Hatcher Cost 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.EggHatcherCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatcher cost by 5%" },
                new ResearchNode { Name = "Egg Hatcher Cost 2", Prerequisites = ["Egg Hatcher Cost 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.EggHatcherCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatcher cost by 5%" },
                new ResearchNode { Name = "Egg Hatcher Cost 3", Prerequisites = ["Egg Hatcher Cost 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.EggHatcherCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatcher cost by 5%" },
                new ResearchNode { Name = "Egg Hatcher Cost 4", Prerequisites = ["Egg Hatcher Cost 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.EggHatcherCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatcher cost by 5%" },
                new ResearchNode { Name = "Egg Hatcher Cost 5", Prerequisites = ["Egg Hatcher Cost 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.EggHatcherCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatcher cost by 5%" },

                new ResearchNode { Name = "Gardening Plot Cost 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningPlotCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening plot cost by 5%" },
                new ResearchNode { Name = "Gardening Plot Cost 2", Prerequisites = ["Gardening Plot Cost 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningPlotCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening plot cost by 5%" },
                new ResearchNode { Name = "Gardening Plot Cost 3", Prerequisites = ["Gardening Plot Cost 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningPlotCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening plot cost by 5%" },
                new ResearchNode { Name = "Gardening Plot Cost 4", Prerequisites = ["Gardening Plot Cost 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningPlotCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening plot cost by 5%" },
                new ResearchNode { Name = "Gardening Plot Cost 5", Prerequisites = ["Gardening Plot Cost 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningPlotCost, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening plot cost by 5%" },

                new ResearchNode { Name = "Reel Timer Duration 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ReelTimerDuration, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases reel timer duration by 5%" },
                new ResearchNode { Name = "Reel Timer Duration 2", Prerequisites = ["Reel Timer Duration 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ReelTimerDuration, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases reel timer duration by 5%" },
                new ResearchNode { Name = "Reel Timer Duration 3", Prerequisites = ["Reel Timer Duration 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ReelTimerDuration, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases reel timer duration by 5%" },
                new ResearchNode { Name = "Reel Timer Duration 4", Prerequisites = ["Reel Timer Duration 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ReelTimerDuration, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases reel timer duration by 5%" },
                new ResearchNode { Name = "Reel Timer Duration 5", Prerequisites = ["Reel Timer Duration 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ReelTimerDuration, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases reel timer duration by 5%" },

                new ResearchNode { Name = "Egg Hatching Duration 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.HatchingDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatching duration by 5%" },
                new ResearchNode { Name = "Egg Hatching Duration 2", Prerequisites = ["Egg Hatching Duration 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.HatchingDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatching duration by 5%" },
                new ResearchNode { Name = "Egg Hatching Duration 3", Prerequisites = ["Egg Hatching Duration 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.HatchingDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatching duration by 5%" },
                new ResearchNode { Name = "Egg Hatching Duration 4", Prerequisites = ["Egg Hatching Duration 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.HatchingDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatching duration by 5%" },
                new ResearchNode { Name = "Egg Hatching Duration 5", Prerequisites = ["Egg Hatching Duration 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.HatchingDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases egg hatching duration by 5%" },

                new ResearchNode { Name = "Gardening Duration 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening duration by 5%" },
                new ResearchNode { Name = "Gardening Duration 2", Prerequisites = ["Gardening Duration 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening duration by 5%" },
                new ResearchNode { Name = "Gardening Duration 3", Prerequisites = ["Gardening Duration 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening duration by 5%" },
                new ResearchNode { Name = "Gardening Duration 4", Prerequisites = ["Gardening Duration 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening duration by 5%" },
                new ResearchNode { Name = "Gardening Duration 5", Prerequisites = ["Gardening Duration 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.GardeningDuration, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases gardening duration by 5%" },

                new ResearchNode { Name = "Unit Quote Interval 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitQuoteInterval, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit quote interval by 5%" },
                new ResearchNode { Name = "Unit Quote Interval 2", Prerequisites = ["Unit Quote Interval 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitQuoteInterval, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit quote interval by 5%" },
                new ResearchNode { Name = "Unit Quote Interval 3", Prerequisites = ["Unit Quote Interval 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitQuoteInterval, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit quote interval by 5%" },
                new ResearchNode { Name = "Unit Quote Interval 4", Prerequisites = ["Unit Quote Interval 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitQuoteInterval, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit quote interval by 5%" },
                new ResearchNode { Name = "Unit Quote Interval 5", Prerequisites = ["Unit Quote Interval 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.UnitQuoteInterval, ModifierType = ModifierType.Percent, ModifierAmount = -0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Decreases unit quote interval by 5%" },

                new ResearchNode { Name = "Item Sell Price 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemSellPrice, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases item sell price by 5%" },
                new ResearchNode { Name = "Item Sell Price 2", Prerequisites = ["Item Sell Price 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemSellPrice, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases item sell price by 5%" },
                new ResearchNode { Name = "Item Sell Price 3", Prerequisites = ["Item Sell Price 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemSellPrice, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases item sell price by 5%" },
                new ResearchNode { Name = "Item Sell Price 4", Prerequisites = ["Item Sell Price 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemSellPrice, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases item sell price by 5%" },
                new ResearchNode { Name = "Item Sell Price 5", Prerequisites = ["Item Sell Price 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ItemSellPrice, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases item sell price by 5%" },

                new ResearchNode { Name = "Experience Boost Amount 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost amount by 5%" },
                new ResearchNode { Name = "Experience Boost Amount 2", Prerequisites = ["Experience Boost Amount 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost amount by 5%" },
                new ResearchNode { Name = "Experience Boost Amount 3", Prerequisites = ["Experience Boost Amount 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost amount by 5%" },
                new ResearchNode { Name = "Experience Boost Amount 4", Prerequisites = ["Experience Boost Amount 3"], Target = 200, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost amount by 5%" },
                new ResearchNode { Name = "Experience Boost Amount 5", Prerequisites = ["Experience Boost Amount 4"], Target = 400, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.ExperienceBoostAmount, ModifierType = ModifierType.Percent, ModifierAmount = 0.05, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases experience boost amount by 5%" },

                new ResearchNode { Name = "Max Unit Level 1", Prerequisites = [], Target = 25, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxUnitLevel, ModifierType = ModifierType.Flat, ModifierAmount = 900, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum unit level by 900" },
                new ResearchNode { Name = "Max Unit Level 2", Prerequisites = ["Max Unit Level 1"], Target = 50, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxUnitLevel, ModifierType = ModifierType.Flat, ModifierAmount = 9000, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum unit level by 9000" },
                new ResearchNode { Name = "Max Unit Level 3", Prerequisites = ["Max Unit Level 2"], Target = 100, Progress = 0, Modifier = new() { ModifierTarget = ModifierTarget.MaxUnitLevel, ModifierType = ModifierType.Flat, ModifierAmount = 90000, ModifierSource = ModifierSource.ResearchNode, ModifierQuantity = 1 } , Description = "Increases maximum unit level by 90000" }
                ];
        }
    }
}