//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Elements.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 25, 25")]
        public global::System.Drawing.Color PrimaryBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimaryBackColor"]));
            }
            set {
                this["PrimaryBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 35, 35")]
        public global::System.Drawing.Color SecondaryBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SecondaryBackColor"]));
            }
            set {
                this["SecondaryBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSeaGreen")]
        public global::System.Drawing.Color MouseOverBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MouseOverBackColor"]));
            }
            set {
                this["MouseOverBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSeaGreen")]
        public global::System.Drawing.Color SelectedBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedBackColor"]));
            }
            set {
                this["SelectedBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 230, 230")]
        public global::System.Drawing.Color PrimaryForeColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimaryForeColor"]));
            }
            set {
                this["PrimaryForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SelectedForeColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedForeColor"]));
            }
            set {
                this["SelectedForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color AccentBackColor {
            get {
                return ((global::System.Drawing.Color)(this["AccentBackColor"]));
            }
            set {
                this["AccentBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color AccentForeColor {
            get {
                return ((global::System.Drawing.Color)(this["AccentForeColor"]));
            }
            set {
                this["AccentForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 200, 120")]
        public global::System.Drawing.Color SuccessTextColor {
            get {
                return ((global::System.Drawing.Color)(this["SuccessTextColor"]));
            }
            set {
                this["SuccessTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color FailureTextColor {
            get {
                return ((global::System.Drawing.Color)(this["FailureTextColor"]));
            }
            set {
                this["FailureTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 70, 70")]
        public global::System.Drawing.Color ErrorTextColor {
            get {
                return ((global::System.Drawing.Color)(this["ErrorTextColor"]));
            }
            set {
                this["ErrorTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160, 160, 220")]
        public global::System.Drawing.Color FlavorTextColor {
            get {
                return ((global::System.Drawing.Color)(this["FlavorTextColor"]));
            }
            set {
                this["FlavorTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 180, 180")]
        public global::System.Drawing.Color CommonRarityColor {
            get {
                return ((global::System.Drawing.Color)(this["CommonRarityColor"]));
            }
            set {
                this["CommonRarityColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 130, 255")]
        public global::System.Drawing.Color RareRarityColor {
            get {
                return ((global::System.Drawing.Color)(this["RareRarityColor"]));
            }
            set {
                this["RareRarityColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 0, 255")]
        public global::System.Drawing.Color EpicRarityColor {
            get {
                return ((global::System.Drawing.Color)(this["EpicRarityColor"]));
            }
            set {
                this["EpicRarityColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color LegendaryRarityColor {
            get {
                return ((global::System.Drawing.Color)(this["LegendaryRarityColor"]));
            }
            set {
                this["LegendaryRarityColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SmallFontSize {
            get {
                return ((int)(this["SmallFontSize"]));
            }
            set {
                this["SmallFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MediumFontSize {
            get {
                return ((int)(this["MediumFontSize"]));
            }
            set {
                this["MediumFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int LargeFontSize {
            get {
                return ((int)(this["LargeFontSize"]));
            }
            set {
                this["LargeFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Padding {
            get {
                return ((int)(this["Padding"]));
            }
            set {
                this["Padding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimestampTextOutput {
            get {
                return ((bool)(this["TimestampTextOutput"]));
            }
            set {
                this["TimestampTextOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 90, 140")]
        public global::System.Drawing.Color WaterTerrainColor {
            get {
                return ((global::System.Drawing.Color)(this["WaterTerrainColor"]));
            }
            set {
                this["WaterTerrainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 120, 60")]
        public global::System.Drawing.Color GrasslandTerrainColor {
            get {
                return ((global::System.Drawing.Color)(this["GrasslandTerrainColor"]));
            }
            set {
                this["GrasslandTerrainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 160, 110")]
        public global::System.Drawing.Color DesertTerrainColor {
            get {
                return ((global::System.Drawing.Color)(this["DesertTerrainColor"]));
            }
            set {
                this["DesertTerrainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 70, 80")]
        public global::System.Drawing.Color MountainTerrainColor {
            get {
                return ((global::System.Drawing.Color)(this["MountainTerrainColor"]));
            }
            set {
                this["MountainTerrainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 95, 95")]
        public global::System.Drawing.Color P1BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P1BuildingColor"]));
            }
            set {
                this["P1BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 165, 70")]
        public global::System.Drawing.Color P2BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P2BuildingColor"]));
            }
            set {
                this["P2BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 225, 90")]
        public global::System.Drawing.Color P3BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P3BuildingColor"]));
            }
            set {
                this["P3BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120, 220, 90")]
        public global::System.Drawing.Color P4BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P4BuildingColor"]));
            }
            set {
                this["P4BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 200, 255")]
        public global::System.Drawing.Color P5BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P5BuildingColor"]));
            }
            set {
                this["P5BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 140, 255")]
        public global::System.Drawing.Color P6BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P6BuildingColor"]));
            }
            set {
                this["P6BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 110, 255")]
        public global::System.Drawing.Color P7BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P7BuildingColor"]));
            }
            set {
                this["P7BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 120, 200")]
        public global::System.Drawing.Color P8BuildingColor {
            get {
                return ((global::System.Drawing.Color)(this["P8BuildingColor"]));
            }
            set {
                this["P8BuildingColor"] = value;
            }
        }
    }
}
